import { PASSIVE_BY_ID } from "./passive-catalog";

export const INTERNAL_PAL_NAMES:Record<string,string>={
  "YakushimaMonster001_Blue":"Blue Slime",
  "YakushimaMonster001_Red":"Red Slime",
  "YakushimaMonster001_Purple":"Purple Slime",
  "YakushimaMonster001_Rainbow":"Rainbow Slime",
  "YakushimaBoss001_Small":"Demon Eye",
  "YakushimaMonster003_Purple":"Illuminant Bat",
  "YakushimaMonster001_Pink":"Illuminant Slime",
  "Alpaca":"Melpaca",
  "AmaterasuWolf":"Kitsun",
  "AmaterasuWolf_Dark":"Kitsun Noct",
  "Anubis":"Anubis",
  "BadCatgirl":"Nyafia",
  "Baphomet":"Incineram",
  "Baphomet_Dark":"Incineram Noct",
  "Bastet":"Mau",
  "Bastet_Ice":"Mau Cryst",
  "BerryGoat":"Caprity",
  "BerryGoat_Dark":"Caprity Noct",
  "BirdDragon":"Vanwyrm",
  "BirdDragon_Ice":"Vanwyrm Cryst",
  "BlackCentaur":"Necromus",
  "BlackGriffon":"Shadowbeak",
  "BlackMetalDragon":"Astegon",
  "BlackPuppy":"Smokie",
  "BlackPuppy_Ice":"Smokie Cryst",
  "BlueDragon":"Azurobe",
  "BlueDragon_Ice":"Azurobe Cryst",
  "BluePlatypus":"Fuack",
  "BluePlatypus_Fire":"Fuack Ignis",
  "BlueSkyDragon":"Shaolong",
  "BlueThunderHorse":"Azurmane",
  "BlueberryFairy":"Prunelia",
  "Boar":"Rushoar",
  "BrownRabbit":"Lapiron",
  "CactusDoll":"Needoll",
  "CactusDoll_Dark":"Needoll Noct",
  "CandleGhost":"Sootseer",
  "CaptainPenguin":"Penking",
  "CaptainPenguin_Black":"Penking Lux",
  "Carbunclo":"Lifmunk",
  "CatBat":"Tombat",
  "CatMage":"Katress",
  "CatMage_Fire":"Katress Ignis",
  "CatVampire":"Felbat",
  "ChickenPal":"Chikipi",
  "ClioneTwins":"Amione",
  "CloverFairy":"Clovee",
  "ClownRabbit":"Dupin",
  "ColorfulBird":"Tocotoco",
  "CowPal":"Mozzarina",
  "CubeTurtle":"Tetroise",
  "CubeTurtle_Neutral":"Tetroise Primo",
  "CuteButterfly":"Cinnamoth",
  "CuteFox":"Vixy",
  "CuteMole":"Fuddler",
  "DandelionGirl":"Souffline",
  "DarkAlien":"Xenovader",
  "DarkCrow":"Cawgnito",
  "DarkFlameFox":"Majex",
  "DarkMechaDragon":"Xenolord",
  "DarkScorpion":"Menasting",
  "DarkScorpion_Ground":"Menasting Terra",
  "Deer":"Eikthyrdeer",
  "Deer_Ground":"Eikthyrdeer Terra",
  "DomeArmorDragon":"Aegidron",
  "DreamDemon":"Daedream",
  "DrillGame":"Digtoise",
  "Eagle":"Galeclaw",
  "ElecCat":"Sparkit",
  "ElecLizard":"Slowatt",
  "ElecPanda":"Grizzbolt",
  "ElecPomeranian":"Puffolt",
  "ElecSnail":"Snock",
  "ElecSnail_Ground":"Snock Lux",
  "FairyDragon":"Elphidran",
  "FairyDragon_Water":"Elphidran Aqua",
  "FeatherOstrich":"Dazemu",
  "FengyunDeeper":"Fenglope",
  "FengyunDeeper_Electric":"Fenglope Lux",
  "FireKirin":"Pyrin",
  "FireKirin_Dark":"Pyrin Noct",
  "FlameBambi":"Rooby",
  "FlameBuffalo":"Arsox",
  "FlowerDinosaur":"Dinossom",
  "FlowerDinosaur_Electric":"Dinossom Lux",
  "FlowerDoll":"Petallia",
  "FlowerDoll_Fire":"Petallia Ignis",
  "FlowerPrince":"Dandilord",
  "FlowerRabbit":"Flopie",
  "FluffyBird":"Muffly",
  "FlyingManta":"Celaray",
  "FlyingManta_Thunder":"Celaray Lux",
  "FoxExorcist":"Flaracle",
  "FoxMage":"Wixen",
  "FoxMage_Dark":"Wixen Noct",
  "Ganesha":"Teafant",
  "Garm":"Direhowl",
  "GhostAnglerfish":"Ghangler",
  "GhostAnglerfish_Fire":"Ghangler Ignis",
  "GhostBeast":"Maraith",
  "GhostBlackCat":"Wispaw",
  "GhostDragon":"Eidrolon",
  "GhostDragon_Fire":"Eidrolon Ignis",
  "GhostRabbit":"Nitemary",
  "GhostRabbit_Grass":"Nitemary Botan",
  "GoldenHorse":"Gildane",
  "Gorilla":"Gorirat",
  "Gorilla_Ground":"Gorirat Terra",
  "GrassGolem":"Dualith",
  "GrassGolem_Dark":"Dualith Noct",
  "GrassMammoth":"Mammorest",
  "GrassMammoth_Ice":"Mammorest Cryst",
  "GrassMinotaur":"Elgrove",
  "GrassMinotaur_Ice":"Elgrove Cryst",
  "GrassPanda":"Mossanda",
  "GrassPanda_Electric":"Mossanda Lux",
  "GrassRabbitMan":"Verdash",
  "GrimGirl":"Splatterina",
  "GuardianDog":"Yakumo",
  "HadesBird":"Helzephyr",
  "HadesBird_Electric":"Helzephyr Lux",
  "HawkBird":"Nitewing",
  "Hedgehog":"Jolthog",
  "Hedgehog_Ice":"Jolthog Cryst",
  "HerculesBeetle":"Warsect",
  "HerculesBeetle_Ground":"Warsect Terra",
  "HoodGhost":"Hoodle",
  "Horus":"Faleris",
  "Horus_Water":"Faleris Aqua",
  "IceCrocodile":"Munchill",
  "IceDeer":"Reindrix",
  "IceFox":"Foxcicle",
  "IceHorse":"Frostallion",
  "IceHorse_Dark":"Frostallion Noct",
  "IceNarwhal":"Whalaska",
  "IceNarwhal_Fire":"Whalaska Ignis",
  "IceSeal":"Polapup",
  "IceSeal_Ground":"Polapup Terra",
  "IceWitch":"Icelyn",
  "JellyfishFairy":"Jelliette",
  "JellyfishGhost":"Jellroy",
  "JetDragon":"Jetragon",
  "KabukiMan":"Renjishi",
  "Kelpie":"Kelpsea",
  "Kelpie_Fire":"Kelpsea Ignis",
  "KendoFrog":"Croajiro",
  "KendoFrog_Dark":"Croajiro Noct",
  "KingAlpaca":"Kingpaca",
  "KingAlpaca_Ice":"Kingpaca Cryst",
  "KingBahamut":"Blazamut",
  "KingBahamut_Dragon":"Blazamut Ryu",
  "KingSunfish":"Solmora",
  "KingSunfish_Thunder":"Solmora Lux",
  "KingWhale":"Panthalus",
  "Kirin":"Univolt",
  "Kirin_Ice":"Univolt Cryst",
  "Kitsunebi":"Foxparks",
  "Kitsunebi_Ice":"Foxparks Cryst",
  "LanternButler":"Loomen",
  "LavaGirl":"Flambelle",
  "LazyCatfish":"Dumud",
  "LazyCatfish_Gold":"Dumud Gild",
  "LazyDragon":"Relaxaurus",
  "LazyDragon_Electric":"Relaxaurus Lux",
  "LeafMomonga":"Herbil",
  "LeafPrincess":"Lullu",
  "LegendDeer":"Hartalis",
  "LilyQueen":"Lyleen",
  "LilyQueen_Dark":"Lyleen Noct",
  "LilyQueen_Ice":"Lyleen Noct",
  "LittleBriarRose":"Bristla",
  "LizardMan":"Leezpunk",
  "LizardMan_Fire":"Leezpunk Ignis",
  "LongCat":"Valentail",
  "LotusDragon":"Ophydia",
  "Manticore":"Blazehowl",
  "Manticore_Dark":"Blazehowl Noct",
  "MimicDog":"Mimog",
  "Monkey":"Tanzee",
  "Monkey_Fire":"Tanzee Ignis",
  "MonochromeQueen":"Solenne",
  "MoonChild":"Wistella",
  "MoonQueen":"Selyne",
  "MopBaby":"Swee",
  "MopKing":"Sweepa",
  "Mothman":"Silvance",
  "MummyPal":"Gildra",
  "MushroomDragon":"Shroomer",
  "MushroomDragon_Dark":"Shroomer Noct",
  "MushroomLady":"Mycora",
  "Mutant":"Lunaris",
  "MysteryMask":"Omascul",
  "NaughtyCat":"Grintale",
  "NegativeKoala":"Depresso",
  "NegativeOctopus":"Killamari",
  "NegativeOctopus_Neutral":"Killamari Primo",
  "NightBlueHorse":"Starryon",
  "NightBlueHorse_Neutral":"Starryon Primo",
  "NightFox":"Nox",
  "NightLady":"Bellanoir",
  "NightLady_Dark":"Bellanoir Libero",
  "NightLady_Pink":"Bellanoir Libero",
  "OctopusGirl":"Gloopie",
  "OctopusGirl_Neutral":"Gloopie Primo",
  "OniGhostGirl":"Bakemi",
  "PandaGirl":"Leafan",
  "Penguin":"Pengullet",
  "Penguin_Electric":"Pengullet Lux",
  "PinkCat":"Cattiva",
  "PinkLizard":"Lovander",
  "PinkRabbit":"Ribbuny",
  "PinkRabbit_Grass":"Ribbuny Botan",
  "PlantSlime":"Gumoss",
  "Plesiosaur":"Braloha",
  "PoseidonOrca":"Neptilius",
  "PurpleSpider":"Tarantriss",
  "QueenBee":"Elizabee",
  "RaijinDaughter":"Dazzi",
  "RaijinDaughter_Water":"Dazzi Noct",
  "RedArmorBird":"Ragnahawk",
  "RedFlowerBird":"Tropicaw",
  "RobinHood":"Robinquill",
  "RobinHood_Ground":"Robinquill Terra",
  "RockBeast":"Pierdon",
  "RockBeast_Ice":"Pierdon Cryst",
  "Ronin":"Bushi",
  "Ronin_Dark":"Bushi Noct",
  "SaintCentaur":"Paladius",
  "SakuraSaurus":"Broncherry",
  "SakuraSaurus_Water":"Broncherry Aqua",
  "SamuraiDog":"Pupperai",
  "ScorpionMan":"Prixter",
  "ScorpionMan_Electric":"Prixter Lux",
  "Sekhmet":"Sekhmet",
  "Serpent":"Surfent",
  "Serpent_Ground":"Surfent Terra",
  "SharkKid":"Gobfin",
  "SharkKid_Fire":"Gobfin Ignis",
  "SheepBall":"Lamball",
  "SifuDog":"Dogen",
  "SkyDragon":"Quivern",
  "SkyDragon_Grass":"Quivern Botan",
  "SleeveRabbit":"Lapure",
  "SmallArmadillo":"Kikit",
  "SmallYeti":"Snugloo",
  "SnakeGirl":"Venusa",
  "SnowPeafowl":"Frostplume",
  "SnowTigerBeastman":"Bastigor",
  "SoldierBee":"Beegarde",
  "StuffedShark":"Finsider",
  "StuffedShark_Fire":"Finsider Ignis",
  "SumoDog":"Bulldosu",
  "Suzaku":"Suzaku",
  "Suzaku_Water":"Suzaku Aqua",
  "SweetsSheep":"Woolipop",
  "SweetsSheep_Ground":"Woolipop Terra",
  "SwordCutlassfish":"Skutlass",
  "SwordCutlassfish_Fire":"Skutlass Ignis",
  "TentacleTurtle":"Turtacle",
  "TentacleTurtle_Ground":"Turtacle Terra",
  "ThiefBird":"Roujay",
  "ThunderBird":"Beakon",
  "ThunderBird_Ice":"Beakon Cryst",
  "ThunderDog":"Rayhound",
  "ThunderDog_Ice":"Rayhound Cryst",
  "ThunderDragonMan":"Orserk",
  "ThunderFluffyBird":"Dynamoff",
  "TropicalOstrich":"Palumba",
  "Umihebi":"Jormuntide",
  "Umihebi_Fire":"Jormuntide Ignis",
  "VenusFlytrap":"Carnibora",
  "VioletFairy":"Vaelet",
  "VolcanicMonster":"Reptyro",
  "VolcanicMonster_Ice":"Reptyro Cryst",
  "VolcanoDragon":"Moldron",
  "VolcanoDragon_Ice":"Moldron Cryst",
  "WeaselDragon":"Chillet",
  "WeaselDragon_Fire":"Chillet Ignis",
  "Werewolf":"Loupmoon",
  "Werewolf_Ice":"Loupmoon Cryst",
  "WhiteAlienDragon":"Xenogard",
  "WhiteDeer":"Celesdir",
  "WhiteDeer_Dark":"Celesdir Noct",
  "WhiteMoth":"Sibelyx",
  "WhiteMoth_Neutral":"Sibelyx Primo",
  "WhiteShieldDragon":"Silvegis",
  "WhiteTiger":"Cryolinx",
  "WhiteTiger_Ground":"Cryolinx Terra",
  "WindChimes":"Hangyu",
  "WindChimes_Ice":"Hangyu Cryst",
  "WingGolem":"Knocklem",
  "WingGolem_Fire":"Knocklem Ignis",
  "WizardOwl":"Hoocrates",
  "WoolFox":"Cremis",
  "WorldTreeDragon":"Astralym",
  "YakushimaBoss001":"Eye of Cthulhu",
  "YakushimaBoss002":"Moonlord",
  "YakushimaMonster001":"Green Slime",
  "YakushimaMonster002":"Enchanted Sword",
  "YakushimaMonster003":"Cave Bat",
  "Yeti":"Wumpo",
  "Yeti_Grass":"Wumpo Botan",
};


const PASSIVE_NAMES:Record<string,string>={
  PAL_ALLAttack_up3:"Deus Inclemente",
  Legend:"Lenda",CraftSpeed_up2:"Artesão",MoveSpeed_up_1:"Ágil",MoveSpeed_up_2:"Corredor",MoveSpeed_up_3:"Veloz",
  Attack_up1:"Valentão",Attack_up2:"Feroz",Attack_up2_2:"Musculoso",Deffence_up1:"Pele Grossa",
  Deffence_up2:"Corpo Robusto",Deffence_up2_2:"Inabalável",WorkSpeed_up1:"Pensamento Positivo",
  WorkSpeed_up2:"Artesão",WorkSpeed_Down1:"Desajeitado",Stamina_up1:"Capacidade Pulmonar",
  Stamina_up2:"Resistência Infinita",Stamina_Down_1:"Frágil",Stamina_Down_2:"Insaciável",
  Food_up1:"Comilão",Food_up2:"Guloso",Food_down1:"Dieta Moderada",Food_down2:"Dieta Rigorosa",
  Sanity_up1:"Estável",Sanity_up2:"Zen",Sanity_Down_1:"Instável",Sanity_Down_2:"Perturbado",
  Rare:"Sortudo",Lucky:"Sortudo",Runner:"Corredor",Swift:"Veloz",Nimble:"Ágil",Artisan:"Artesão"
};

export type ImportedPal={name:string;count:number;passives:string[];sex?:string;playerId:string;playerName:string};
type AnyObject=Record<string,unknown>;
const isObject=(v:unknown):v is AnyObject=>!!v&&typeof v==="object"&&!Array.isArray(v);
const valueOf=(v:unknown):unknown=>isObject(v)&&"value" in v?v.value:v;
const guid=(s:string)=>s.toLowerCase();
const internalName=(raw:string)=>{
  const clean=raw.replace(/^BOSS_/,"").replace(/^GYM_/,"");
  return INTERNAL_PAL_NAMES[clean]||clean;
};
export const passiveName=(raw:string)=>{
  const clean=raw.replace(/^PassiveSkill_/i,"");
  if(PASSIVE_NAMES[clean])return PASSIVE_NAMES[clean];
  return clean.replace(/_/g," ").replace(/\b(up|down)\s*(\d+)?\b/gi,(_,d,n)=>d.toLowerCase()==="up"?` +${n||""}`:` -${n||""}`).replace(/\s+/g," ").trim();
};
function collectPlayerIds(value:unknown,out:Set<string>,depth=0){
  if(depth>16||value==null)return;
  if(Array.isArray(value)){value.forEach(v=>collectPlayerIds(v,out,depth+1));return}
  if(!isObject(value))return;
  if("PlayerUId" in value){const candidate=valueOf(value.PlayerUId);if(typeof candidate==="string"&&candidate!=="00000000-0000-0000-0000-000000000000")out.add(guid(candidate))}
  Object.values(value).forEach(v=>collectPlayerIds(v,out,depth+1));
}
type LevelRecord={save:AnyObject;recordPlayerId?:string};
function levelRecords(json:AnyObject):LevelRecord[]{
  const p=isObject(json.properties)?json.properties:{};const world=valueOf(p.worldSaveData);
  const map=isObject(world)?valueOf(world.CharacterSaveParameterMap):undefined;
  if(!Array.isArray(map))return[];
  return map.map(entry=>{
    const e=isObject(entry)?entry:{};const key=isObject(e.key)?e.key:{};const keyPlayer=valueOf(key.PlayerUId);const ev=valueOf(e.value);const raw=isObject(ev)?valueOf(ev.RawData):undefined;
    const object=isObject(raw)?raw.object:undefined;const save=isObject(object)?valueOf(object.SaveParameter):undefined;
    return isObject(save)?{save,recordPlayerId:typeof keyPlayer==="string"?guid(keyPlayer):undefined}:null;
  }).filter((x):x is LevelRecord=>!!x);
}
export async function importPalFiles(files:File[],validNames:Set<string>){
  const usable=files.filter(f=>!/_dps\.json$/i.test(f.name)&&/\.json$/i.test(f.name)).sort((a,b)=>a.size-b.size);
  const playerIds=new Set<string>();let level:AnyObject|undefined;let failed=0;
  for(const file of usable){try{const json=JSON.parse(await file.text()) as AnyObject;if(/(^|\/)level\.json$/i.test(file.name))level=json;else collectPlayerIds(json,playerIds)}catch{failed++}}
  if(!level){return{pals:[] as ImportedPal[],recognized:0,unmapped:0,failed,ignored:files.length-usable.length,players:playerIds.size}}
  const records=levelRecords(level);const playerNames=new Map<string,string>();
  records.forEach(({save,recordPlayerId})=>{if(valueOf(save.IsPlayer)===true&&recordPlayerId){const nick=valueOf(save.NickName);const filtered=valueOf(save.FilteredNickName);const name=typeof nick==="string"&&nick.trim()?nick:typeof filtered==="string"&&filtered.trim()?filtered:"Jogador";playerNames.set(recordPlayerId,name)}});
  const owners=playerIds.size?playerIds:new Set(records.map(({save})=>valueOf(save.OwnerPlayerUId)).filter((x):x is string=>typeof x==="string"&&!!x).map(guid));
  const pals:ImportedPal[]=[];let unmapped=0;
  for(const {save:r} of records){const owner=valueOf(r.OwnerPlayerUId);if(typeof owner!=="string"||!owners.has(guid(owner)))continue;const playerId=guid(owner);
    const character=valueOf(r.CharacterID);if(typeof character!=="string")continue;const name=internalName(character);
    if(!validNames.has(name)){unmapped++;continue}
    const passiveWrap=valueOf(r.PassiveSkillList);const values=isObject(passiveWrap)&&Array.isArray(passiveWrap.values)?passiveWrap.values:[];
    const passives=values.filter((x):x is string=>typeof x==="string"&&!!PASSIVE_BY_ID[x]);
    const genderWrap=valueOf(r.Gender);const gender=isObject(genderWrap)?valueOf(genderWrap.value):genderWrap;
    const sex=typeof gender==="string"?(gender.endsWith("Male")?"Macho":gender.endsWith("Female")?"Fêmea":gender):undefined;
    pals.push({name,count:1,passives,sex,playerId,playerName:playerNames.get(playerId)||`Jogador ${playerId.slice(0,8).toUpperCase()}`});
  }
  return{pals,recognized:pals.length,unmapped,failed,ignored:files.length-usable.length,players:owners.size};
}
